### ISSUE TITLE
Icons are wack

### ISSUE THREAD

**Issue by Vaulto350** [LimeGradient/ModProfiles#2]
They're just really wack and breaking everything

**Comment by DasshuDev** [comment]
this is being fixed

**Comment by DasshuDev** [comment]
@Vaulto350 on second thought, are you running the latest gh build?

**Comment by Vaulto350** [comment]
@JayDasshu No. I'm running the most recent Geode build (Android)

**Comment by LimeGradient** [comment]
@Vaulto350 are you using Mod Profiles from the index or from github

**Comment by Vaulto350** [comment]
@LimeGradient 

Index.

**Comment by LimeGradient** [comment]
@Vaulto350 can you attach a screenshot of what you mean by the icons are wack?
